name: 'Install Dependencies'
description: 'Install dependencies for Tauri project'
runs:
  using: 'composite'
  steps:
    # 安装 Windows 特定依赖
    - name: Install Windows dependencies
      if: runner.os == 'Windows'
      shell: powershell
      run: |
        choco install --no-progress windows-sdk-10.0
        # 确保 WebView2 Runtime 已安装
        choco install --no-progress microsoft-edge-webview2-runtime

    # 安装 macOS 特定依赖
    - name: Install macOS dependencies
      if: runner.os == 'macOS'
      shell: bash
      run: |
        xcode-select --install || true
        brew install cmake llvm

    # 安装 Linux 特定依赖
    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf libssl-dev libayatana-appindicator3-dev
        # 安装其他可能需要的依赖
        sudo apt-get install -y build-essential pkg-config libx11-dev libasound2-dev libudev-dev