name: 'Install Dependencies'
description: 'Install dependencies for Tauri project'
runs:
  using: 'composite'
  steps:
    # 安装 Windows 特定依赖
    - name: Install Windows dependencies
      if: runner.os == 'Windows'
      shell: powershell
      run: |
        choco install --no-progress windows-sdk-10.0
        # 尝试安装 WebView2 Runtime，但即使失败也继续执行
        try {
          # 直接从chocolatey安装，不指定特殊源
          choco install --no-progress microsoft-edge-webview2-runtime
        } catch {
          # 如果安装失败，记录警告并继续
          Write-Warning "WebView2 Runtime installation failed, continuing with build process"
        }
        # 无论WebView2安装成功与否，都返回成功退出码
        exit 0

    # 安装 macOS 特定依赖
    - name: Install macOS dependencies
      if: runner.os == 'macOS'
      shell: bash
      run: |
        xcode-select --install || true
        brew install cmake llvm

    # 安装 Linux 特定依赖
    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        # 仅安装 libayatana-appindicator3-dev（与 libappindicator3-dev 冲突）
        # 在 Ubuntu 24.04 上使用 libwebkit2gtk-4.1-dev
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev librsvg2-dev patchelf libssl-dev libayatana-appindicator3-dev
        # 安装其他可能需要的依赖
        sudo apt-get install -y build-essential pkg-config libx11-dev libasound2-dev libudev-dev